### ISSUE TITLE
Allow introspecting number of messages in queue

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo#4] opened 2015-04-24 19:30 UTC
Useful to detect stalls, rough estimate of system load and bottlenecks.

Requires new APIs in Transport. Acceptable that they are polling based?

Would be provided as edge metadata in Flowhub, so it can be visualized there?

**Comment by bergie** [comment] 2015-04-24 20:17
With RabbitMQ we can use the [Management API](http://hg.rabbitmq.com/rabbitmq-management/raw-file/3646dee55e02/priv/www-api/help.html)

**Comment by bergie** [comment] 2015-10-05 22:53
[guv](https://github.com/the-grid/guv) provides facilities for this now.

**Comment by bergie** [comment] 2017-05-03 10:37
Dupe of #29

**Closed by bergie** 2017-05-03 10:37 UTC
Labels: enhancement
